SELECT 
    T1.CODUSUR AS "Código do Vendedor", T1.NOME AS "Nome",
    TO_CHAR(SUM(T2.QT * T2.PVENDA),'FM999G999G999D90') AS "Total Venda"
FROM 
	PCUSUARI T1

INNER JOIN PCPEDI T2 ON T2.CODUSUR = T1.CODUSUR
INNER JOIN PCPRODUT T3 ON T3.CODPROD = T2.CODPROD 
INNER JOIN PCPEDC T4 ON T4.NUMPED  = T2.NUMPED

WHERE
	
	T2.DATA BETWEEN (:DataI) AND TO_DATE(:DataF)
AND
 	T1.CODUSUR = :CodRCA
AND
	T3.CODEPTO IN (10010,10013)
AND 
	T4.CODFILIAL IN (1,2,7,9,24)

GROUP BY
    T1.CODUSUR,
    t1.NOME 
ORDER BY
    T1.CODUSUR;
