SELECT 
CODUSUR as RCA, NOME, 
DECODE(VLVENDA, 0, 0, DECODE(PERCENTUALMETA, 0, 0, NVL(ROUND((((VLLUCRO / VLVENDA) * 100) / PERCENTUALMETA) * 100),0))) as margem
FROM
( 
    SELECT
    	PCPEDC.CODUSUR,VEND.NOME,
    	SUM(I.QT * I.PVENDA) VLVENDA, SUM((I.QT * I.PVENDA) - (PCPEDC.VLCUSTOFIN/PCPEDC.NUMITENS)) VLLUCRO, TO_NUMBER(NVL(MAX(VEND.FAX),0), '9999.99') AS PERCENTUALMETA 
    FROM  PCPEDC 
        LEFT JOIN PCUSUARI VEND ON VEND.CODUSUR = PCPEDC.CODUSUR
        INNER JOIN PCPEDI I ON I.NUMPED = PCPEDC.NUMPED
        INNER JOIN PCPRODUT P ON P.CODPROD = I.CODPROD 
    WHERE PCPEDC.CONDVENDA NOT IN (4, 8, 10, 13, 20, 98, 99) 
        AND PCPEDC.DTCANCEL IS NULL 
        AND PCPEDC.DATA BETWEEN :dt1 AND :dt2 
        AND PCPEDC.CODFILIAL IN ('1','2','7','9','24')
        AND NVL(P.CODLINHAPROD,1) NOT IN ( 36,37,38,39,40,41,44,45 )
    GROUP BY PCPEDC.CODUSUR, VEND.NOME
)